
services:
  db:
    image: postgres:15
    container_name: eb3_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-eb3}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-eb3pass}
      POSTGRES_DB: ${POSTGRES_DB:-eb3jobs}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-eb3} -d ${POSTGRES_DB:-eb3jobs}"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build: .
    container_name: eb3_api
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
